config/routes.rb
Rails.application.routes.draw do
  get 'gasza_admin', to: 'administrator#index'
  get 'gasza_admin/monitor', to: 'administrator#monitor'
  get 'gasza_admin/topup', to: 'administrator#topup'

  get 'terms/term_of_services'

  get 'terms/privacy_policy'

  get 'terms/refund_policy'

  get 'setting/index'

  get 'verify_user/index'
  get 'verify_user', to: 'verify_user#index'

  get 'contact/index'
  get 'contact', to: 'contact#index'

  get 'order_history/index'
  get 'order_history', to: 'order_history#index'
  get 'order_refresh', to: 'order_history#refresh'

  post 'order_update', to: 'order_history#update_order'
  post 'order_cancel', to: 'order_history#cancel_order'
  post 'report_instance', to: 'order_history#report_instance'

  post 'update_user_notification', to: 'home#update_user_notification'
  post 'cancel_user_notification', to: 'home#cancel_user_notification'

  post 'load_notification', to: 'home#load_notification'
  post 'update_notification_seen', to: 'home#update_notification_seen'
  post 'update_notification_read_all', to: 'home#update_notification_read_all'

  get 'transaction_history/index'
  get 'transaction_history', to: 'transaction_history#index'

  get 'setting/index'
  get 'setting', to: 'setting#index'

  get 'notification/:id', to: 'home#redirect_noti'

  get 'topup/index'
  get 'topup', to: 'topup#index'
  post 'topup_true', to: 'topup#create_true'
  get 'topup_true_verify', to: 'topup#verify_true'
  post 'topup_paypal_verify', to: 'topup#verify_paypal'
  post 'topup_debit', to: 'topup#create_debit'

  get 'home/index'
  get 'home', to: 'home#index'
  post 'create_order', to: 'home#create_order'
  post 'cancel_order', to: 'home#cancel_order'

  get 'reg/index'
  get 'reg', to: 'reg#index'
  post 'reg', to: 'reg#create'

  post 'change_password', to: 'reg#change_password'
  post 'user_signin', to: 'reg#user_signin'
  get 'logout', to: 'reg#logout'

  get 'main/index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :check_userlogin

  def index
  end

  private

  def check_userlogin
    if current_user
      redirect_to '/home'
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<script src='https://www.google.com/recaptcha/api.js?hl=th'></script>
<div id='main_head_container'>
  <%= image_tag('welcomebackground.jpg', id: 'main_head_img') %>
  <div id='main_wrapper'>
    <div id='main_left_pannel'>
      <div id='register_pannel'>
        <h3 id='reg_head'>สมาชิกใหม่</h3>
        <%= form_tag('/reg', id: 'reg_form', remote: true, authenticity_token: true, :multipart => true, enctype: 'application/json') do %>
            <% reg_key = $data_reg.keys.sample %>
            <% dummies0 = rand(3).times.collect{|i| (0...5).map{ $ooo[rand($ooo.length)] }.join } %>
            <% dummies1 = rand(3).times.collect{|i| (0...5).map{ $ooo[rand($ooo.length)] }.join } %>
            <% dummies2 = rand(3).times.collect{|i| (0...5).map{ $ooo[rand($ooo.length)] }.join } %>
            <% dummies3 = rand(3).times.collect{|i| (0...5).map{ $ooo[rand($ooo.length)] }.join } %>
            <% dummies4 = rand(3).times.collect{|i| (0...5).map{ $ooo[rand($ooo.length)] }.join } %>
            <%
               def random_input_by_id(id)
                 {
                   0=> ((text_field_tag id.to_sym, nil, placeholder: 'Username')).html_safe,
                   1=> ((password_field_tag id.to_sym, nil, placeholder: 'Password')).html_safe,
                   2=> ((password_field_tag id.to_sym, nil, placeholder: 'Password Confirmation')).html_safe,
                   3=> (email_field(id.to_sym, nil, placeholder: 'Email', name: id, id: id)).html_safe,
                 }[rand(4)]
               end
            %>
            <style>
              #<%= $data_reg[reg_key][:a] %>, #<%= $data_reg[reg_key][:b] %>, #<%= $data_reg[reg_key][:c] %>, #<%= $data_reg[reg_key][:d] %>_ {
                border: 1px solid #BBBBBB;
                font-size: 10pt;
                padding: 6px;
                width: 100%;
                color: #555555;
                margin-top: 4px;
              }
              <%= (dummies0+dummies1+dummies2+dummies3+dummies4).flatten.collect{|h| '#'+h }.join(', ') %> {
                width: 1px;
                height: 1px;
                border: none;
                position: absolute;
                visibility: hidden;
              }
            </style>
            <%= hidden_field_tag 'regk', reg_key %>
            <%= dummies0.collect{|a| random_input_by_id(a)}.join().html_safe %>
            <%= text_field_tag $data_reg[reg_key][:a].to_sym, nil, placeholder: 'Username' %><br>
            <%= dummies1.collect{|a| random_input_by_id(a)}.join().html_safe %>
            <%= password_field_tag $data_reg[reg_key][:b].to_sym, nil, placeholder: 'Password' %><br>
            <%= dummies2.collect{|a| random_input_by_id(a)}.join().html_safe %>
            <%= password_field_tag $data_reg[reg_key][:c].to_sym, nil, placeholder: 'Password Confirmation' %><br>
            <%= dummies3.collect{|a| random_input_by_id(a)}.join().html_safe %>
            <%= email_field($data_reg[reg_key][:d].to_sym, nil, placeholder: 'Email', name: $data_reg[reg_key][:d]) %><br>
            <%= dummies4.collect{|a| random_input_by_id(a)}.join().html_safe %>
          <br>
          <span style="font-size: 10px;">ในการสมัครใช้งาน เราถือว่าคุณเข้าใจและยอมรับ <a href="<%= terms_term_of_services_path %>">ข้อตกลงในการให้บริการ</a>, <a href="<%= terms_privacy_policy_path %>">นโยบายความเป็นส่วนตัว</a> &amp; <a href="<%= terms_refund_policy_path %>">นโยบายการคืนเงินและคืนสินค้าหรือบริการ</a> ของ Playdigger</span><br><br>
          <%= submit_tag 'ลงทะเบียน', id: 'reg_submit', class: 'g-recaptcha', data: { sitekey: '6Lf6AyEUAAAAAOsxg8dO-ulwiIJ447h3mASQR7jL', callback: 'regSubmit' } %>
        <% end %>
      </div>
    </div>
    <div id='main_right_pannel'>
      <div id='right_ad_pannel'>
        <div class='blank_ad'></div>
        <div class='right_ad orange'>
          <h4><i class="far fa-cloud"></i></h4>
          <span>ไร้โปรแกรม</span>
        </div>
        <div class='blank_ad'></div>

        <div class='right_ad white'>
          <h4><i class="far fa-key"></i></h4>
          <span>ปลอดภัย</span>
        </div>

        <div class='blank_ad'></div>

        <div class='right_ad orange'>
          <h4><i class="far fa-flask"></i></h4>
          <span>ทดลองฟรี</span>
        </div>

        <div class='blank_ad'></div>
        <div class='blank_ad'></div>
        <div class='blank_ad'></div>

        <div class='right_ad blue'>
          <h4><i class="far fa-clock"></i></h4>
          <span>รวดเร็ว</span>
        </div>

        <div class='right_ad orange'>
          <h4><i class="far fa-thumbs-up"></i></h4>
          <span>ถูก</span>
        </div>

        <div class='blank_ad'></div>

        <div class='right_ad white'>
          <h4><i class="far fa-heart"></i></h4>
          <span>บริการด้วยใจ</span>
        </div>

        <div class='blank_ad'></div>
        <div class='blank_ad'></div>

        <div class='right_ad white'>
          <h4><i class="far fa-eye"></i></h4>
          <span>อัพเดตตลอด</span>
        </div>

        <div class='blank_ad'></div>
        <div class='blank_ad'></div>

        <div class='right_ad blue'>
          <h4><i class="far fa-trophy"></i></h4>
          <span>น่าเชื่อถือ</span>
        </div>


        <div class='blank_ad'></div>
        <div class='blank_ad'></div>
      </div>

    </div>
  </div>
</div>
<div id='main_content'>
  <span id='main_x_head'>บริการขุด <span style='color: #FF4F0F;'>PLAYSERVER</span></span>
  <div id='main_detail_container'>
    <div id='detail_free' class='detail_item'>
      <h4><i class="far fa-flask"></i></h4>
      <h3>ทดลองใช้ฟรี</h3>
      <ul>
        <li>สมัครสมาชิกใหม่และทดลองใช้ฟรี</li>
        <li>เพิ่มความมั่นใจในบริการด้วยการทดลองด้วยตนเองก่อนจ่ายเงินซื้อบริการขุด</li>
      </ul>
      <a href='<%= reg_path %>' id='detail_reg'>สมัครสมาชิก</a>
    </div>
    <div id='detail_price' class='detail_item'>
      <h4><i class="far fa-thumbs-up"></i></h4>
      <h3>มีคุณภาพและราคาถูก</h3>
      <ul>
        <li>ราคาถูกที่สุดที่ให้บริการอยู่</li>
        <li>การันตี แต้มเข้าครบถ้วน</li>
        <li>อัพเดตสถานะให้เห็นแบบเรียลไทม์</li>
        <li>ขุดเร็ว ไม่ต้องรอนาน</li>
      </ul>
    </div>
    <div id='detail_cloud' class='detail_item'>
      <h4><i class="far fa-cloud"></i></h4>
      <h3>ไม่ต้องใช้โปรแกรม</h3>
      <ul>
        <li>ไม่ต้องเปิดโปรแกรมหรือคอมพิวเตอร์ทิ้งไว้</li>
        <li>แค่คลิกเดียวแล้วรอคะแนนเข้าระบบได้เลย</li>
        <li>เป็นระบบอัตโนมัติทั้งหมด ไม่ต้องรอแอดมินตอบรับก่อนใช้บริการ</li>
      </ul>
    </div>
  </div>
</div>
<div id='price_content'>
  <span id='price_x_head'>ค่าบริการ</span>
  <div id='price_detail_container'>
    <table id='price_detail'>
      <thead>
        <tr>
          <td>อัตราค่าบริการ (บาท)</td>
          <td>จำนวนแต้มขุด (โหวต)</td>
          <td>ระยะเวลาที่ใช้ (ประมาณ) *</td>
        </tr>
      </thead>
      <% true_multiplier = 20 %>
      <tbody>
        <tr>
          <td>ฟรี</td>
          <td><%= BONUS_NEW_ACCOUNT %></td>
          <td>5 นาที</td>
        </tr>
        <tr>
          <td>50</td>
          <td><%= 50*true_multiplier%></td>
          <td>5 นาที</td>
        </tr>
        <tr>
          <td>90</td>
          <td><%= 90*true_multiplier%></td>
          <td>5 นาที</td>
        </tr>
        <tr>
          <td>150</td>
          <td><%= 150*true_multiplier%></td>
          <td>5 นาที</td>
        </tr>
        <tr>
          <td>300</td>
          <td><%= 300*true_multiplier%></td>
          <td>7 นาที</td>
        </tr>
        <tr>
          <td>500</td>
          <td><%= 500*true_multiplier%></td>
          <td>13 นาที</td>
        </tr>
        <tr>
          <td>1000</td>
          <td><%= 1000*true_multiplier %></td>
          <td>25 นาที</td>
        </tr>
      </tbody>
    </table>
  </div>
  <span id='ps_price'>* หมายเหตุ : ระยะเวลาที่ใช้อาจคลาดเคลื่อนได้ ในกรณีที่มีคิวในการบริการสูง</span>
</div>