config/routes.rb
Rails.application.routes.draw do
  get 'gasza_admin', to: 'administrator#index'
  get 'gasza_admin/monitor', to: 'administrator#monitor'
  get 'gasza_admin/topup', to: 'administrator#topup'

  get 'terms/term_of_services'

  get 'terms/privacy_policy'

  get 'terms/refund_policy'

  get 'setting/index'

  get 'verify_user/index'
  get 'verify_user', to: 'verify_user#index'

  get 'contact/index'
  get 'contact', to: 'contact#index'

  get 'order_history/index'
  get 'order_history', to: 'order_history#index'
  get 'order_refresh', to: 'order_history#refresh'

  post 'order_update', to: 'order_history#update_order'
  post 'order_cancel', to: 'order_history#cancel_order'
  post 'report_instance', to: 'order_history#report_instance'

  post 'update_user_notification', to: 'home#update_user_notification'
  post 'cancel_user_notification', to: 'home#cancel_user_notification'

  post 'load_notification', to: 'home#load_notification'
  post 'update_notification_seen', to: 'home#update_notification_seen'
  post 'update_notification_read_all', to: 'home#update_notification_read_all'

  get 'transaction_history/index'
  get 'transaction_history', to: 'transaction_history#index'

  get 'setting/index'
  get 'setting', to: 'setting#index'

  get 'notification/:id', to: 'home#redirect_noti'

  get 'topup/index'
  get 'topup', to: 'topup#index'
  post 'topup_true', to: 'topup#create_true'
  get 'topup_true_verify', to: 'topup#verify_true'
  post 'topup_paypal_verify', to: 'topup#verify_paypal'
  post 'topup_debit', to: 'topup#create_debit'

  get 'home/index'
  get 'home', to: 'home#index'
  post 'create_order', to: 'home#create_order'
  post 'cancel_order', to: 'home#cancel_order'

  get 'reg/index'
  get 'reg', to: 'reg#index'
  post 'reg', to: 'reg#create'

  post 'change_password', to: 'reg#change_password'
  post 'user_signin', to: 'reg#user_signin'
  get 'logout', to: 'reg#logout'

  get 'main/index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transaction_history_controller.rb
class TransactionHistoryController < ApplicationController
  def index
    @total = MoneyTransaction.where(:user_id => current_user.id).count
    @total_page = (@total % 10) > 0 ? (@total / 10)+1 : (@total / 10)
    @page = (params['page'] || 1).to_i
  end
end

app/helpers/transaction_history_helper.rb
module TransactionHistoryHelper
end

app/views/transaction_history/index.html.erb
<% unless current_user.is_confirmed %>
  <div id='announce'>
    <span>กรุณายืนยัน Email เพื่อรับเครดิตสำหรับการทดลองใช้ <%= BONUS_NEW_ACCOUNT %> คะแนนโหวต</span>
  </div>
<% end %>
<div id='home_container'>
  <div id='home_navi'>
    <a href='<%= home_path %>' class='navi'>หน้าแรก</a>
    <a href='<%= topup_path %>' class='navi'>เติมเงิน</a>
    <a href='<%= transaction_history_path %>' class='navi active'>ประวัติการเติมเงิน</a>
    <a href='<%= order_history_path %>' class='navi'>ประวัติการใช้บริการ</a>
    <a href='<%= contact_path %>' class='navi'>ติดต่อ</a>
    <a href='<%= setting_path %>' class='navi'>ตั้งค่า</a>
  </div>

  <div id='home_main_content'>
    <div id='home_head'>
      <span id='text_rim'>ประวัติการเติมเงิน</span>
    </div>
    <hr>
    <div id='transaction_detail_container'>
      <table id='transaction_detail'>
        <thead>
          <tr>
            <td width="20%">เวลา</td>
            <td width="20%">สถานะ</td>
            <td width="20%">รหัส</td>
            <td width="10%">ราคา</td>
            <td width="20%">เครดิต</td>
            <td width="10%">ช่องทาง</td>
          </tr>
        </thead>
        <tbody>
          <% MoneyTransaction.where(:user_id => current_user.id).order(:created_time => :desc).limit(10).offset((@page-1)*10).each do |ttrns| %>
            <tr>
              <td><%= Time.at(ttrns.created_time).strftime('%D %r') %></td>
              <td><%=
                case ttrns.status
                when 'A'
                  '<span style="color: #9A762F;">กำลังตรวจสอบ</span>'.html_safe
                when 'B'
                  '<span style="color: #4C9A2F;">ยืนยัน</span>'.html_safe
                when 'C'
                  '<span style="color: #9A3030;">ล้มเหลว</span>'.html_safe
                end
              %></td>
              <td><%= ttrns.password || '-' %></td>
              <td><%= ttrns.price || '-' %></td>
              <td><%= ttrns.amount || '-' %></td>
              <td><%=
                case ttrns.topup_type
                when "true"
                  "TRUEM"
                when "paypal"
                  "PAYPA"
                when "debit"
                  "TRANS"
                end
              %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div id='paginateWrapper'>
        <a href='<%= @page == 1 ? '#' : '?page='+(@page-1).to_s %>' class='paginate <%= @page == 1 ? 'active' : '' %>'>&#60;</a>
          <% @total_page.times do |i| %>
            <a href='?page=<%= i+1 %>' class='paginate <%= @page == i+1 ? 'active' : '' %>'><%= i+1 %></a>
          <% end %>
        <a href='<%= (@page*10) >= @total ? '#' : '?page='+(@page+1).to_s %>' class='paginate <%= (@page*10) >= @total ? 'active' : '' %>'>&#62;</a>
      </div>
    </div>
  </div>
</div>