config/routes.rb
Rails.application.routes.draw do
  get 'gasza_admin', to: 'administrator#index'
  get 'gasza_admin/monitor', to: 'administrator#monitor'
  get 'gasza_admin/topup', to: 'administrator#topup'

  get 'terms/term_of_services'

  get 'terms/privacy_policy'

  get 'terms/refund_policy'

  get 'setting/index'

  get 'verify_user/index'
  get 'verify_user', to: 'verify_user#index'

  get 'contact/index'
  get 'contact', to: 'contact#index'

  get 'order_history/index'
  get 'order_history', to: 'order_history#index'
  get 'order_refresh', to: 'order_history#refresh'

  post 'order_update', to: 'order_history#update_order'
  post 'order_cancel', to: 'order_history#cancel_order'
  post 'report_instance', to: 'order_history#report_instance'

  post 'update_user_notification', to: 'home#update_user_notification'
  post 'cancel_user_notification', to: 'home#cancel_user_notification'

  post 'load_notification', to: 'home#load_notification'
  post 'update_notification_seen', to: 'home#update_notification_seen'
  post 'update_notification_read_all', to: 'home#update_notification_read_all'

  get 'transaction_history/index'
  get 'transaction_history', to: 'transaction_history#index'

  get 'setting/index'
  get 'setting', to: 'setting#index'

  get 'notification/:id', to: 'home#redirect_noti'

  get 'topup/index'
  get 'topup', to: 'topup#index'
  post 'topup_true', to: 'topup#create_true'
  get 'topup_true_verify', to: 'topup#verify_true'
  post 'topup_paypal_verify', to: 'topup#verify_paypal'
  post 'topup_debit', to: 'topup#create_debit'

  get 'home/index'
  get 'home', to: 'home#index'
  post 'create_order', to: 'home#create_order'
  post 'cancel_order', to: 'home#cancel_order'

  get 'reg/index'
  get 'reg', to: 'reg#index'
  post 'reg', to: 'reg#create'

  post 'change_password', to: 'reg#change_password'
  post 'user_signin', to: 'reg#user_signin'
  get 'logout', to: 'reg#logout'

  get 'main/index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  before_action :check_userlogin

  def index
  end

  def monitor
    @data = ($redis.lrange("playdigger:queue",0,100).collect{|g| [g, 'group'] }+OrderTransaction.where(is_finished: false, is_limit: true).collect{|t| [t.id.to_s+"#-#"+t.order_key, 'solo'] }).collect do |t,ty|
      {
        type: ty,
        key: t,
        current: $redis.get(t).to_i,
        credit: $redis.get(t+":credit").to_i,
        to_dig: $redis.get(t+":to_dig").to_i
      }
    end.sort_by{|h| h[:credit] - h[:current]} rescue []
  end

  private

  def check_userlogin
    unless current_user && current_user.id == 1
      redirect_to '/'
    end
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/views/administrator/index.html.erb
<div id='admin_container'>
  <div id='admin_wrapper'>
    <a class='admin_nav' href='<%= gasza_admin_monitor_path %>'>มอนิเตอร์ระบบ</a>
    <a class='admin_nav' href='<%= gasza_admin_topup_path %>'>เติมเงิน</a>
  </div>
</div>

app/views/administrator/monitor.html.erb
<div id='admin_container'>
  <div id='admin_wrapper'>
    <table>
      <thead>
        <tr>
          <td>server</td>
          <td>type</td>
          <td>current</td>
          <td>credit</td>
          <td>to_dig</td>
        </tr>
      </thead>
      <tbody>
        <% (@data || []).each do |data| %>
          <tr>
            <td class='servername'><%= data[:key] %></td>
            <td><%= data[:type] %></td>
            <td><%= data[:current] %></td>
            <td><%= data[:credit] %></td>
            <td><%= data[:to_dig] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/administrator/topup.html.erb
<div id='admin_container'>
  <div id='admin_wrapper'>
    <%= form_tag('/topup_debit', id: 'gas_topup', remote: true, authenticity_token: true, :multipart => true, enctype: 'application/json') do %>
      <%= text_field_tag :username, nil, placeholder: 'Username', class: 'admin_input' %>
      <%= text_field_tag :price, nil, placeholder: 'Price', class: 'admin_input' %>
      <%= text_field_tag :promotion, nil, placeholder: 'Promotion', class: 'admin_input' %>
      <%= submit_tag 'เติมเงิน', id: 'admin_submit_btn' %>
    <% end %>
  </div>
</div>